# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2001Members(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None):
        """
        InlineResponse2001Members - a model defined in Swagger

        :param id: The id of this InlineResponse2001Members.
        :type id: int
        """
        self.swagger_types = {
            'id': int
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001Members':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_members of this InlineResponse2001Members.
        :rtype: InlineResponse2001Members
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this InlineResponse2001Members.

        :return: The id of this InlineResponse2001Members.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this InlineResponse2001Members.

        :param id: The id of this InlineResponse2001Members.
        :type id: int
        """

        self._id = id

