# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response2001_members import InlineResponse2001Members
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2001(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, members: List[InlineResponse2001Members]=None):
        """
        InlineResponse2001 - a model defined in Swagger

        :param message: The message of this InlineResponse2001.
        :type message: str
        :param members: The members of this InlineResponse2001.
        :type members: List[InlineResponse2001Members]
        """
        self.swagger_types = {
            'message': str,
            'members': List[InlineResponse2001Members]
        }

        self.attribute_map = {
            'message': 'message',
            'members': 'members'
        }

        self._message = message
        self._members = members

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.
        :rtype: InlineResponse2001
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this InlineResponse2001.

        :return: The message of this InlineResponse2001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this InlineResponse2001.

        :param message: The message of this InlineResponse2001.
        :type message: str
        """

        self._message = message

    @property
    def members(self) -> List[InlineResponse2001Members]:
        """
        Gets the members of this InlineResponse2001.

        :return: The members of this InlineResponse2001.
        :rtype: List[InlineResponse2001Members]
        """
        return self._members

    @members.setter
    def members(self, members: List[InlineResponse2001Members]):
        """
        Sets the members of this InlineResponse2001.

        :param members: The members of this InlineResponse2001.
        :type members: List[InlineResponse2001Members]
        """

        self._members = members

