# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse201(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, message: str=None):
        """
        InlineResponse201 - a model defined in Swagger

        :param id: The id of this InlineResponse201.
        :type id: int
        :param message: The message of this InlineResponse201.
        :type message: str
        """
        self.swagger_types = {
            'id': int,
            'message': str
        }

        self.attribute_map = {
            'id': 'id',
            'message': 'message'
        }

        self._id = id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.
        :rtype: InlineResponse201
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this InlineResponse201.

        :return: The id of this InlineResponse201.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this InlineResponse201.

        :param id: The id of this InlineResponse201.
        :type id: int
        """

        self._id = id

    @property
    def message(self) -> str:
        """
        Gets the message of this InlineResponse201.

        :return: The message of this InlineResponse201.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this InlineResponse201.

        :param message: The message of this InlineResponse201.
        :type message: str
        """

        self._message = message

